<?php

if (!class_exists('Oc3dAig_ImageUtils')) {

    class Oc3dAig_ImageUtils {
        
        public static function getSettings(){
            $image_setting = get_option(OC3DAIG_PREFIX_LOW . 'image_generator',  array());
            return  array(
	'Artist'          => array(
		'id'              => OC3DAIG_PREFIX_LOW .'artist_opt',
		'option_selected' => isset( $image_setting[OC3DAIG_PREFIX_LOW .'artist_opt'] ) ? $image_setting[OC3DAIG_PREFIX_LOW .'artist_opt'] : 'Salvador Dalí',
		'option'          => array(
			'Salvador Dalí'             => 'Salvador Dalí',
			'Leonardo da Vinci'         => 'Leonardo da Vinci',
			'Michelangelo'              => 'Michelangelo',
			'Albrecht Dürer'            => 'Albrecht Dürer',
			'Alfred Sisley'             => 'Alfred Sisley',
			'Andrea Mantegna'           => 'Andrea Mantegna',
			'Andy Warhol'               => 'Andy Warhol',
			'Amedeo Modigliani'         => 'Amedeo Modigliani',
			'Camille Pissarro'          => 'Camille Pissarro',
			'Caravaggio'                => 'Caravaggio',
			'Caspar David Friedrich'    => 'Caspar David Friedrich',
			'Cézanne'                   => 'Cézanne',
			'Claude Monet'              => 'Diego Velázquez',
			'Eugène Delacroix'          => 'Eugène Delacroix',
			'Frida Kahlo'               => 'Frida Kahlo',
			'Gustav Klimt'              => 'Gustav Klimt',
			'Henri Matisse'             => 'Henri Matisse',
			'Henri de Toulouse-Lautrec' => 'Henri de Toulouse-Lautrec',
			'Jackson Pollock'           => 'Jackson Pollock',
			'Jasper Johns'              => 'Jasper Johns',
			'Joan Miró'                 => 'Joan Miró',
			'John Singer Sargent'       => 'John Singer Sargent',
			'Johannes Vermeer'          => 'Johannes Vermeer',
			'Mary Cassatt'              => 'Mary Cassatt',
			'M. C. Escher'              => 'M. C. Escher',
			'Paul Cézanne'              => 'Paul Cézanne',
			'Paul Gauguin'              => 'Paul Gauguin',
			'Paul Klee'                 => 'Paul Klee',
			'Pierre-Auguste Renoir'     => 'Pierre-Auguste Renoir',
			'Pieter Bruegel the Elder'  => 'Pieter Bruegel the Elder',
			'Piet Mondrian'             => 'Piet Mondrian',
			'Pablo Picasso'             => 'Pablo Picasso',
			'Rembrandt'                 => 'Rembrandt',
			'René Magritte'             => 'René Magritte',
			'Raphael'                   => 'Raphael',
			'Sandro Botticelli'         => 'Sandro Botticelli',
			'Titian'                    => 'Titian',
			'Theo van Gogh'             => 'Theo van Gogh',
			'Vincent van Gogh'          => 'Vincent van Gogh',
			'Vassily Kandinsky'         => 'Vassily Kandinsky',
			'Winslow Homer'             => 'Winslow Homer',
			'None'                      => 'None',
		),
	),
	'Style'           => array(
		'id'              => OC3DAIG_PREFIX_LOW .'style_opt',
		'option_selected' => isset( $image_setting[OC3DAIG_PREFIX_LOW .'style_opt'] ) ? $image_setting[OC3DAIG_PREFIX_LOW .'style_opt'] : 'Surrealism',
		'option'          => array(
			'Surrealism'             => 'Surrealism',
			'Abstract'               => 'Abstract',
			'Abstract Expressionism' => 'Abstract Expressionism',
			'Action painting'        => 'Action painting',
			'Art Brut'               => 'Art Brut',
			'Art Deco'               => 'Art Deco',
			'Art Nouveau'            => 'Art Nouveau',
			'Baroque'                => 'Baroque',
			'Byzantine'              => 'Byzantine',
			'Classical'              => 'Classical',
			'Color Field'            => 'Color Field',
			'Conceptual'             => 'Conceptual',
			'Cubism'                 => 'Cubism',
			'Dada'                   => 'Dada',
			'Expressionism'          => 'Expressionism',
			'Fauvism'                => 'Fauvism',
			'Figurative'             => 'Figurative',
			'Futurism'               => 'Futurism',
			'Gothic'                 => 'Gothic',
			'Hard-edge painting'     => 'Hard-edge painting',
			'Hyperrealism'           => 'Hyperrealism',
			'Impressionism'          => 'Impressionism',
			'Japonisme'              => 'Japonisme',
			'Luminism'               => 'Luminism',
			'Lyrical Abstraction'    => 'Lyrical Abstraction',
			'Mannerism'              => 'Mannerism',
			'Minimalism'             => 'Minimalism',
			'Naive Art'              => 'Naive Art',
			'New Realism'            => 'New Realism',
			'Neo-expressionism'      => 'Neo-expressionism',
			'Neo-pop'                => 'Neo-pop',
			'Op Art'                 => 'Op Art',
			'Opus Anglicanum'        => 'Opus Anglicanum',
			'Outsider Art'           => 'Outsider Art',
			'Pop Art'                => 'Pop Art',
			'Photorealism'           => 'Photorealism',
			'Pointillism'            => 'Pointillism',
			'Post-Impressionism'     => 'Post-Impressionism',
			'Realism'                => 'Realism',
			'Renaissance'            => 'Renaissance',
			'Rococo'                 => 'Rococo',
			'Romanticism'            => 'Romanticism',
			'Street Art'             => 'Street Art',
			'Superflat'              => 'Superflat',
			'Symbolism'              => 'Symbolism',
			'Tenebrism'              => 'Tenebrism',
			'Ukiyo-e'                => 'Ukiyo-e',
			'Western Art'            => 'Western Art',
			'YBA'                    => 'YBA',
			'None'                   => 'None',
		),
	),
	'Photography'     => array(
		'id'              => OC3DAIG_PREFIX_LOW .'photography_opt',
		'option_selected' => isset( $image_setting[OC3DAIG_PREFIX_LOW .'photography_opt'] ) ? $image_setting[OC3DAIG_PREFIX_LOW .'photography_opt'] : 'Portrait',
		'option'          => array(
			'Portrait'         => 'Portrait',
			'Landscape'        => 'Landscape',
			'Abstract'         => 'Abstract',
			'Action'           => 'Action',
			'Aerial'           => 'Aerial',
			'Agricultural'     => 'Agricultural',
			'Animal'           => 'Animal',
			'Architectural'    => 'Architectural',
			'Architectural'    => 'Architectural',
			'Astrophotography' => 'Astrophotography',
			'Bird photography' => 'Bird photography',
			'Black and white'  => 'Black and white',
			'Candid'           => 'Candid',
			'Cityscape'        => 'Cityscape',
			'Close-up'         => 'Close-up',
			'Commercial'       => 'Commercial',
			'Conceptual'       => 'Conceptual',
			'Corporate'        => 'Corporate',
			'Documentary'      => 'Documentary',
			'Event'            => 'Event',
			'Family'           => 'Family',
			'Fashion'          => 'Fashion',
			'Fine art'         => 'Fine art',
			'Food'             => 'Food',
			'Food photography' => 'Food photography',
			'Glamour'          => 'Glamour',
			'Industrial'       => 'Industrial',
			'Lifestyle'        => 'Lifestyle',
			'Macro'            => 'Macro',
			'Nature'           => 'Nature',
			'Night'            => 'Night',
			'Product'          => 'Product',
			'Sports'           => 'Sports',
			'Street'           => 'Street',
			'Travel'           => 'Travel',
			'Underwater'       => 'Underwater',
			'Wedding'          => 'Wedding',
			'Wildlife'         => 'Wildlife',
			'None'             => 'None',
		),
	),
	'Lighting'        => array(
		'id'              => OC3DAIG_PREFIX_LOW .'lighting_opt',
		'option_selected' => isset( $image_setting[OC3DAIG_PREFIX_LOW .'lighting_opt'] ) ? $image_setting[OC3DAIG_PREFIX_LOW .'lighting_opt'] : 'Ambient',
		'option'          => array(
			'Ambient'           => 'Ambient',
			'Artificial light'  => 'Artificial light',
			'Backlight'         => 'Backlight',
			'Black light'       => 'Black light',
			'Black light'       => 'Black light',
			'Candle light'      => 'Candle light',
			'Chiaroscuro'       => 'Chiaroscuro',
			'Cloudy'            => 'Cloudy',
			'Cloudy'            => 'Cloudy',
			'Continuous light'  => 'Continuous light',
			'Contre-jour'       => 'Contre-jour',
			'Direct light'      => 'Direct light',
			'Direct sunlight'   => 'Direct sunlight',
			'Diffused light'    => 'Diffused light',
			'Firelight'         => 'Firelight',
			'Flash'             => 'Flash',
			'Flat light'        => 'Flat light',
			'Fluorescent'       => 'Fluorescent',
			'Fog'               => 'Fog',
			'Front light'       => 'Front light',
			'Golden hour'       => 'Golden hour',
			'Hard light'        => 'Hard light',
			'Hazy sunlight'     => 'Hazy sunlight',
			'High key'          => 'High key',
			'Incandescent'      => 'Incandescent',
			'Key light'         => 'Key light',
			'LED'               => 'LED',
			'Low key'           => 'Low key',
			'Moonlight'         => 'Moonlight',
			'Natural light'     => 'Natural light',
			'Neon'              => 'Neon',
			'Open shade'        => 'Open shade',
			'Overcast'          => 'Overcast',
			'Paramount'         => 'Paramount',
			'Party lights'      => 'Party lights',
			'Photoflood'        => 'Photoflood',
			'Quarter light'     => 'Quarter light',
			'Reflected light'   => 'Reflected light',
			'Reflected light'   => 'Reflected light',
			'Shaded'            => 'Shaded',
			'Shaded light'      => 'Shaded light',
			'Silhouette'        => 'Silhouette',
			'Silhouette'        => 'Silhouette',
			'Silhouette'        => 'Silhouette',
			'Softbox'           => 'Softbox',
			'Soft light'        => 'Soft light',
			'Split lighting'    => 'Split lighting',
			'Stage lighting'    => 'Stage lighting',
			'Studio light'      => 'Studio light',
			'Sunburst'          => 'Sunburst',
			'Tungsten'          => 'Tungsten',
			'Umbrella lighting' => 'Umbrella lighting',
			'Underexposed'      => 'Underexposed',
			'Venetian blinds'   => 'Venetian blinds',
			'Warm light'        => 'Warm light',
			'White balance'     => 'White balance',
			'None'              => 'None',
		),
	),
	'Camera'          => array(
		'id'              => OC3DAIG_PREFIX_LOW .'camera_opt',
		'option_selected' => isset( $image_setting[OC3DAIG_PREFIX_LOW .'camera_opt'] ) ? $image_setting[OC3DAIG_PREFIX_LOW .'camera_opt'] : 'Aperture',
		'option'          => array(
			'Aperture'                        => 'Aperture',
			'Active D-Lighting'               => 'Active D-Lighting',
			'Auto Exposure Bracketing'        => 'Auto Exposure Bracketing',
			'Auto Focus Mode'                 => 'Auto Focus Mode',
			'Auto Focus Point'                => 'Auto Focus Point',
			'Auto Lighting Optimizer'         => 'Auto Lighting Optimizer',
			'Auto Rotate'                     => 'Auto Rotate',
			'Aspect Ratio'                    => 'Aspect Ratio',
			'Audio Recording'                 => 'Audio Recording',
			'Auto ISO'                        => 'Auto ISO',
			'Chromatic Aberration Correction' => 'Chromatic Aberration Correction',
			'Color Space'                     => 'Color Space',
			'Continuous Shooting'             => 'Continuous Shooting',
			'Distortion Correction'           => 'Distortion Correction',
			'Drive Mode'                      => 'Drive Mode',
			'Dynamic Range'                   => 'Dynamic Range',
			'Exposure Compensation'           => 'Exposure Compensation',
			'Flash Mode'                      => 'Flash Mode',
			'Focus Mode'                      => 'Focus Mode',
			'Focus Peaking'                   => 'Focus Peaking',
			'Frame Rate'                      => 'Frame Rate',
			'GPS'                             => 'GPS',
			'Grid Overlay'                    => 'Grid Overlay',
			'High Dynamic Range'              => 'High Dynamic Range',
			'Highlight Tone Priority'         => 'Highlight Tone Priority',
			'Image Format'                    => 'Image Format',
			'Image Stabilization'             => 'Image Stabilization',
			'Interval Timer Shooting'         => 'Interval Timer Shooting',
			'ISO'                             => 'ISO',
			'ISO Auto Setting'                => 'ISO Auto Setting',
			'Lens Correction'                 => 'Lens Correction',
			'Live View'                       => 'Live View',
			'Long Exposure Noise Reduction'   => 'Long Exposure Noise Reduction',
			'Manual Focus'                    => 'Manual Focus',
			'Metering Mode'                   => 'Metering Mode',
			'Movie Mode'                      => 'Movie Mode',
			'Movie Quality'                   => 'Movie Quality',
			'Noise Reduction'                 => 'Noise Reduction',
			'Picture Control'                 => 'Picture Control',
			'Picture Style'                   => 'Picture Style',
			'Quality'                         => 'Quality',
			'Self-Timer'                      => 'Self-Timer',
			'Shutter Speed'                   => 'Shutter Speed',
			'Time-lapse Interval'             => 'Time-lapse Interval',
			'Time-lapse Recording'            => 'Time-lapse Recording',
			'Virtual Horizon'                 => 'Virtual Horizon',
			'Video Format'                    => 'Video Format',
			'White Balance'                   => 'White Balance',
			'Zebra Stripes'                   => 'Zebra Stripes',
			'None'                            => 'None',
		),
	),
	'Composition'     => array(
		'id'              => OC3DAIG_PREFIX_LOW .'composition_opt',
		'option_selected' => isset( $image_setting[OC3DAIG_PREFIX_LOW .'composition_opt'] ) ? $image_setting[OC3DAIG_PREFIX_LOW .'composition_opt'] : 'Composition',
		'option'          => array(
			'Rule of Thirds'         => 'Rule of Thirds',
			'Asymmetrical'           => 'Asymmetrical',
			'Balance'                => 'Balance',
			'Centered'               => 'Centered',
			'Close-up'               => 'Close-up',
			'Color blocking'         => 'Color blocking',
			'Contrast'               => 'Contrast',
			'Cropping'               => 'Cropping',
			'Diagonal'               => 'Diagonal',
			'Documentary'            => 'Documentary',
			'Environmental Portrait' => 'Environmental Portrait',
			'Fill the Frame'         => 'Fill the Frame',
			'Framing'                => 'Framing',
			'Golden Ratio'           => 'Golden Ratio',
			'High Angle'             => 'High Angle',
			'Leading Lines'          => 'Leading Lines',
			'Long Exposure'          => 'Long Exposure',
			'Low Angle'              => 'Low Angle',
			'Macro'                  => 'Macro',
			'Minimalism'             => 'Minimalism',
			'Negative Space'         => 'Negative Space',
			'Panning'                => 'Panning',
			'Patterns'               => 'Patterns',
			'Photojournalism'        => 'Photojournalism',
			'Point of View'          => 'Point of View',
			'Portrait'               => 'Portrait',
			'Reflections'            => 'Reflections',
			'Saturation'             => 'Saturation',
			'Scale'                  => 'Scale',
			'Selective Focus'        => 'Selective Focus',
			'Shallow Depth of Field' => 'Shallow Depth of Field',
			'Silhouette'             => 'Silhouette',
			'Simplicity'             => 'Simplicity',
			'Snapshot'               => 'Snapshot',
			'Street Photography'     => 'Street Photography',
			'Symmetry'               => 'Symmetry',
			'Telephoto'              => 'Telephoto',
			'Texture'                => 'Texture',
			'Tilt-Shift'             => 'Tilt-Shift',
			'Time-lapse'             => 'Time-lapse',
			'Tracking Shot'          => 'Tracking Shot',
			'Travel'                 => 'Travel',
			'Triptych'               => 'Triptych',
			'Ultra-wide'             => 'Ultra-wide',
			'Vanishing Point'        => 'Vanishing Point',
			'Viewpoint'              => 'Viewpoint',
			'Vintage'                => 'Vintage',
			'Wide Angle'             => 'Wide Angle',
			'Zoom Blur'              => 'Zoom Blur',
			'Zoom In/Zoom Out'       => 'Zoom In/Zoom Out',
			'None'                   => 'None',
		),
	),
	'Resolution'      => array(
		'id'              => OC3DAIG_PREFIX_LOW .'resolution_opt',
		'option_selected' => isset( $image_setting[OC3DAIG_PREFIX_LOW .'resolution_opt'] ) ? $image_setting[OC3DAIG_PREFIX_LOW .'resolution_opt'] : '4K (3840x2160)',
		'option'          => array(
			'4K (3840x2160)'    => '4K (3840x2160)',
			'1080p (1920x1080)' => '1080p (1920x1080)',
			'720p (1280x720)'   => '720p (1280x720)',
			'480p (854x480)'    => '480p (854x480)',
			'2K (2560x1440)'    => '2K (2560x1440)',
			'1080i (1920x1080)' => '1080i (1920x1080)',
			'720i (1280x720)'   => '720i (1280x720)',
			'None'              => 'None',
		),
	),
	'Color'           => array(
		'id'              => OC3DAIG_PREFIX_LOW .'color_opt',
		'option_selected' => isset( $image_setting[OC3DAIG_PREFIX_LOW .'color_opt'] ) ? $image_setting[OC3DAIG_PREFIX_LOW .'color_opt'] : 'RGB',
		'option'          => array(
			'RGB'       => 'RGB',
			'CMYK'      => 'CMYK',
			'Grayscale' => 'Grayscale',
			'HEX'       => 'HEX',
			'CMY'       => 'CMY',
			'HSL'       => 'HSL',
			'HSV'       => 'HSV',
			'LAB'       => 'LAB',
			'LCH'       => 'LCH',
			'LUV'       => 'LUV',
			'XYZ'       => 'XYZ',
			'YUV'       => 'YUV',
			'YIQ'       => 'YIQ',
			'YCbCr'     => 'YCbCr',
			'YPbPr'     => 'YPbPr',
			'YDbDr'     => 'YDbDr',
			'YCoCg'     => 'YCoCg',
			'YCgCo'     => 'YCgCo',
			'YCC'       => 'YCC',
			'None'      => 'None',
		),
	),
	'Special effects' => array(
		'id'              => OC3DAIG_PREFIX_LOW .'special-effects_opt',
		'option_selected' => isset( $image_setting[OC3DAIG_PREFIX_LOW .'special-effects_opt'] ) ? $image_setting[OC3DAIG_PREFIX_LOW .'special-effects_opt'] : 'Cinemagraph',
		'option'          => array(
			'Cinemagraph'             => 'Cinemagraph',
			'3D'                      => '3D',
			'Add Noise'               => 'Add Noise',
			'Black and White'         => 'Black and White',
			'Blur'                    => 'Blur',
			'Bokeh'                   => 'Bokeh',
			'Brightness and Contrast' => 'Brightness and Contrast',
			'Camera Shake'            => 'Camera Shake',
			'Clarity'                 => 'Clarity',
			'Color Balance'           => 'Color Balance',
			'Color Pop'               => 'Color Pop',
			'Color Temperature'       => 'Color Temperature',
			'Cross Processing'        => 'Cross Processing',
			'Crop and Rotate'         => 'Crop and Rotate',
			'Dehaze'                  => 'Dehaze',
			'Denoise'                 => 'Denoise',
			'Diffuse Glow'            => 'Diffuse Glow',
			'Displace'                => 'Displace',
			'Distort'                 => 'Distort',
			'Double exposure'         => 'Double exposure',
			'Duotone'                 => 'Duotone',
			'Edge Detection'          => 'Edge Detection',
			'Emboss'                  => 'Emboss',
			'Exposure'                => 'Exposure',
			'Fish Eye'                => 'Fish Eye',
			'Flare'                   => 'Flare',
			'Flip'                    => 'Flip',
			'Fractalius'              => 'Fractalius',
			'Glowing Edges'           => 'Glowing Edges',
			'Gradient Map'            => 'Gradient Map',
			'Grayscale'               => 'Grayscale',
			'Halftone'                => 'Halftone',
			'HDR'                     => 'HDR',
			'HDR Look'                => 'HDR Look',
			'High Pass'               => 'High Pass',
			'Hue and Saturation'      => 'Hue and Saturation',
			'Impressionist'           => 'Impressionist',
			'Infrared'                => 'Infrared',
			'Invert'                  => 'Invert',
			'Lens Correction'         => 'Lens Correction',
			'Lens flare'              => 'Lens flare',
			'Lomo Effect'             => 'Lomo Effect',
			'Motion Blur'             => 'Motion Blur',
			'Night Vision'            => 'Night Vision',
			'Oil Painting'            => 'Oil Painting',
			'Old Photo'               => 'Old Photo',
			'Orton Effect'            => 'Orton Effect',
			'Panorama'                => 'Panorama',
			'Pinch'                   => 'Pinch',
			'Pixelate'                => 'Pixelate',
			'Polar Coordinates'       => 'Polar Coordinates',
			'Posterize'               => 'Posterize',
			'Radial Blur'             => 'Radial Blur',
			'Rain'                    => 'Rain',
			'Reflect'                 => 'Reflect',
			'Ripple'                  => 'Ripple',
			'Sharpen'                 => 'Sharpen',
			'Slow motion'             => 'Slow motion',
			'Stop-motion'             => 'Stop-motion',
			'Solarize'                => 'Solarize',
			'Starburst'               => 'Starburst',
			'Sunburst'                => 'Sunburst',
			'Timelapse'               => 'Timelapse',
			'Tilt-shift'              => 'Tilt-shift',
			'Vignette'                => 'Vignette',
			'Zoom blur'               => 'Zoom blur',
			'None'                    => 'None',
		),
	),
	'Size'            => array(
		'id'              => OC3DAIG_PREFIX_LOW .'size_opt',
		'option_selected' => isset( $image_setting[OC3DAIG_PREFIX_LOW .'size_opt'] ) ? $image_setting[OC3DAIG_PREFIX_LOW .'size_opt'] : '1024x1024',
		'option'          => array(
			'256x256'   => '256x256',
			'512x512'   => '512x512',
			'1024x1024' => '1024x1024',
		),
	),
	'Models'            => array(
		'id'              => OC3DAIG_PREFIX_LOW .'models_opt',
		'option_selected' => isset( $image_setting[OC3DAIG_PREFIX_LOW .'models_opt'] ) ? $image_setting[OC3DAIG_PREFIX_LOW .'models_opt'] : 'Dall-E 3',
		'option'          => array(
			'dall-e-3'   => 'dall-e-3',
			'dall-e-2'   => 'dall-e-2',
			
		),
	),
	
);
        }
        
        public static function getSettingsKeys(){
            return array(
                    'oc3daig_artist_opt',
                    'oc3daig_camera_opt',
                    'oc3daig_color_opt',
                    'oc3daig_composition_opt',
                    'oc3daig_lighting_opt',
                    'oc3daig_models_opt',
                    'oc3daig_photography_opt',
                    'oc3daig_resolution_opt',
                    'oc3daig_size_opt',
                    'oc3daig_special-effects_opt',
                    'oc3daig_style_opt'
                );
        }
        
        public static function getImageCountVars(){
            return [1,2,3,4,5,6,7,8,9];
        }
        
        public static function getPromptExamples(){
            return ['Design a mythical realm with floating islands and magical creatures.',
            'Create a futuristic metropolis bustling with innovative technology.',
            'Illustrate an enchanting world beneath the ocean\'s surface.',
            'Depict an astronaut discovering a new planet.',
            'Design an industrial, steam-powered cityscape.',
            'Paint a forest where trees glow with mystical energy.',
            'Visualize a scene showcasing a journey through time.',
            'Create characters melding human and machine elements.',
            'Craft an extraterrestrial terrain with bizarre flora and fauna.',
            'Illustrate a majestic castle atop a hill surrounded by a medieval village.',
            'Bleak future city with oppressive architecture.',
            'Scene featuring creatures from different mythologies interacting.',
            'Paint a sustainable city thriving in harmony with nature.',
            'Visualize an expedition through underground caverns.',
            'Illustrate a hidden pirate bay with ships and treasure.',
            'Create a spooky, abandoned mansion shrouded in mystery.',
            'Bird\'s-eye view of mountains, rivers, and forests.',
            'Desolate landscape after a global catastrophe.',
            'Illustrate a team of superheroes fighting against a common enemy.',
            'Create a whimsical land made entirely of sweets and treats.',
            'Visualize a clash between giant robots in a futuristic arena.',
            'Illustrate mysterious ruins from an ancient civilization.',
            'Surreal dreamscape with floating islands and surreal elements.',
            'Create a serene snowy landscape with cozy cottages.',
            'Design an elaborate airship soaring through the sky.',
            'Illustrate a garden where plants grow in peculiar shapes.',
            'Visualize a city reclaimed by nature after years of abandonment.',
            'Spaceship journeying through a cosmic wormhole.',
            'Create a castle straight out of a fairy tale with turrets and spires.',
            'Robotic insects inspired by real insects.',
            'Scenes from Greek myths featuring gods and heroes.',
            'Paint a dense jungle teeming with exotic wildlife.',
            'Visualize an underground city bustling with life.',
            'Create a towering wizard\'s residence surrounded by magic.',
            'Illustrate a bustling, neon-lit street in a cyberpunk world.',
            'Design an abandoned space station drifting in space.',
            'Ethereal beings in a celestial realm.',
            'Remnants of a lost civilization hidden in a jungle.',
            'Cave adorned with treasure guarded by a mighty dragon.',
            'High-tech sports event in a futuristic stadium.',
            'Serene tropical island with crystal-clear waters.',
            'Grand library filled with ancient and magical books.',
            'Machine capable of traversing through time.',
            'Vibrant circus scene with performers and animals.',
            'Cityscape with gravity-defying architecture.',
            'AI entities interacting in a digital world.',
            'Scenes showing different realities coexisting.',
            'Paint a magical waterfall in a mystical forest.',
            'Depict a futuristic observatory studying cosmic phenomena.',
            'Illustrate ethereal creatures embodying different aspects of nature.',
                ];
        }
        
    }

}